version: '2.1'

services:
  huginn_web:
    build:
      context: ../../
      dockerfile: docker/single-process/Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: huginn
      APP_SECRET_TOKEN: 3bd139f9186b31a85336bb89cd1a1337078921134b2f48e022fd09c234d764d3e19b018b2ab789c6e0e04a1ac9e3365116368049660234c2038dc9990513d49c
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_PORT_3306_TCP_PORT: 3306
    depends_on:
      - db
    restart: unless-stopped

  huginn_threaded:
    build:
      context: ../../
      dockerfile: docker/single-process/Dockerfile
    environment:
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: huginn
      APP_SECRET_TOKEN: 3bd139f9186b31a85336bb89cd1a1337078921134b2f48e022fd09c234d764d3e19b018b2ab789c6e0e04a1ac9e3365116368049660234c2038dc9990513d49c
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_PORT_3306_TCP_PORT: 3306
    command: /docker/scripts/init bin/threaded.rb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: huginn
      MYSQL_PASSWORD: huginn
      MYSQL_DATABASE: huginn
    restart: unless-stopped
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  dbvolume:
