version: '2.1'

services:
  huginn_web:
    image: cantino/huginn-single-process
    ports:
      - 3000:3000
    extends:
      file: environment.yml
      service: huginn_base
    environment:
      DATABASE_ADAPTER: postgresql
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PORT_5432_TCP_PORT: 5432
    depends_on:
      - db
    restart: unless-stopped

  huginn_threaded:
    image: cantino/huginn-single-process
    extends:
      file: environment.yml
      service: huginn_base
    environment:
      DATABASE_ADAPTER: postgresql
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PORT_5432_TCP_PORT: 5432
    command: /docker/scripts/init bin/threaded.rb
    depends_on:
      - db
    restart: unless-stopped
    
  # huginn_schedule:
  #   image: cantino/huginn-single-process
  #   extends:
  #     file: environment.yml
  #     service: huginn_base
  #   environment:
  #     DATABASE_ADAPTER: postgresql
  #     POSTGRES_PORT_5432_TCP_ADDR: db
  #     POSTGRES_PORT_5432_TCP_PORT: 5432
  #   command: /docker/scripts/init bin/schedule.rb
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  # huginn_twitter_stream:
  #   image: cantino/huginn-single-process
  #   extends:
  #     file: environment.yml
  #     service: huginn_base
  #   environment:
  #     DATABASE_ADAPTER: postgresql
  #     POSTGRES_PORT_5432_TCP_ADDR: db
  #     POSTGRES_PORT_5432_TCP_PORT: 5432
  #   command: /docker/scripts/init bin/twitter_stream.rb
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  # huginn_dj1:
  #   image: cantino/huginn-single-process
  #   extends:
  #     file: environment.yml
  #     service: huginn_base
  #   environment:
  #     DATABASE_ADAPTER: db
  #     POSTGRES_PORT_5432_TCP_ADDR: db
  #     POSTGRES_PORT_5432_TCP_PORT: 5432
  #   command: /docker/scripts/init script/delayed_job run
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: huginn
      POSTGRES_PASSWORD: huginn
      POSTGRES_DB: huginn
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - dbvolume:/var/lib/postgresql/data/pgdata

volumes:
  dbvolume:
